<template>
  <div class="page">
    <v-card flat class="hero pa-5 mb-4"><div class="d-flex flex-wrap align-center"><div><div class="text-overline">BUSINESS INTELLIGENCE</div><h1 class="text-h5 font-weight-bold">Reports</h1><div class="grey--text">Review sales, collections, receivables and property inventory.</div></div><v-spacer/><v-btn icon :loading="loading" @click="load"><v-icon>mdi-refresh</v-icon></v-btn></div></v-card>
    <v-alert v-if="error" type="error" dense text>{{ error }}</v-alert>
    <v-row><v-col v-for="card in cards" :key="card.label" cols="12" sm="6" md="3"><v-card outlined class="fill-height"><v-card-text><div class="caption grey--text text-uppercase">{{ card.label }}</div><div class="text-h5 font-weight-bold mt-1">{{ card.money ? money(metrics[card.key]) : metrics[card.key] || 0 }}</div></v-card-text></v-card></v-col></v-row>
    <v-row class="mt-2"><v-col cols="12" md="6"><v-card outlined><v-card-title>Monthly Collections</v-card-title><v-card-text><div v-if="!monthly.length" class="empty">No collection data.</div><div v-for="row in monthly" :key="row.month" class="mb-4"><div class="d-flex justify-space-between caption"><span>{{ row.month }}</span><strong>{{ money(row.amount) }}</strong></div><v-progress-linear class="mt-1" rounded :value="percent(row.amount)" color="primary"/></div></v-card-text></v-card></v-col><v-col cols="12" md="6"><v-card outlined><v-card-title>Property Inventory</v-card-title><v-list dense><v-list-item v-for="row in inventory" :key="row.label"><v-list-item-content>{{ row.label }}</v-list-item-content><v-list-item-action><v-chip small outlined>{{ row.value }}</v-chip></v-list-item-action></v-list-item></v-list></v-card></v-col></v-row>
  </div>
</template>
<script>
import api from '../../../services/api'
export default {name:'Reports',data:()=>({loading:false,error:'',metrics:{},monthly:[],inventory:[],cards:[{label:'Sales Value',key:'sales_value',money:true},{label:'Collections',key:'collections',money:true},{label:'Receivables',key:'receivables',money:true},{label:'Overdue Amount',key:'overdue_amount',money:true}]}),computed:{max(){return Math.max(...this.monthly.map(r=>Number(r.amount||0)),1)}},mounted(){this.load()},methods:{async load(){this.loading=true;this.error='';try{const r=await api.get('/sales/dashboard');const d=r.data||{};this.metrics=d.metrics||{};this.monthly=d.monthly_collections||[];const m=this.metrics;this.inventory=[{label:'Available',value:m.available_properties||0},{label:'Reserved',value:m.reserved_properties||0},{label:'Booked',value:m.booked_properties||0},{label:'Sold',value:m.sold_properties||0},{label:'Overdue Installments',value:m.overdue_count||0}]}catch(e){this.error=e.response?.data?.message||'Unable to load reports.'}finally{this.loading=false}},money(v){return new Intl.NumberFormat('en-PK',{maximumFractionDigits:0}).format(Number(v||0))},percent(v){return Number(v||0)/this.max*100}}}
</script>
<style scoped>.page{width:100%}.hero{border-left:4px solid #165134}.empty{min-height:120px;display:flex;align-items:center;justify-content:center;color:#888}</style>
