<template>
  <div class="page">
    <v-card flat class="hero pa-5 mb-4"><div class="d-flex flex-wrap align-center"><div><div class="text-overline">BUSINESS INTELLIGENCE</div><h1 class="text-h5 font-weight-bold">Financial & Business Reports</h1><div class="grey--text">Sales, collections, receivables and overdue installment monitoring.</div></div><v-spacer/><v-btn icon :loading="loading" @click="load"><v-icon>mdi-refresh</v-icon></v-btn></div></v-card>
    <v-alert v-if="error" type="error" dense text>{{ error }}</v-alert>
    <v-row><v-col v-for="card in cards" :key="card.label" cols="12" sm="6" md="3"><v-card outlined class="fill-height"><v-card-text><div class="caption grey--text text-uppercase">{{ card.label }}</div><div class="text-h5 font-weight-bold mt-1">{{ card.money ? money(metrics[card.key]) : metrics[card.key] || 0 }}</div></v-card-text></v-card></v-col></v-row>
    <v-card outlined class="mt-5"><v-card-title>Outstanding Receivables <v-spacer/><v-switch v-model="overdueOnly" inset dense label="Overdue only" @change="loadReceivables"/></v-card-title><v-data-table :headers="receivableHeaders" :items="receivables" :loading="receivableLoading" :items-per-page="15"><template v-slot:item.due_date="{item}">{{ item.due_date | dateOnly }}</template><template v-slot:item.amount="{item}">{{ money(item.amount) }}</template><template v-slot:item.paid_amount="{item}">{{ money(item.paid_amount) }}</template><template v-slot:item.remaining_amount="{item}"><strong>{{ money(item.remaining_amount) }}</strong></template><template v-slot:item.status="{item}"><v-chip x-small :color="isOverdue(item)?'error':(item.status==='partial'?'orange':'primary')" outlined>{{ isOverdue(item)?'overdue':item.status }}</v-chip></template><template v-slot:no-data><div class="pa-8 grey--text">No outstanding installments.</div></template></v-data-table></v-card>
    <v-row class="mt-2"><v-col cols="12" md="6"><v-card outlined><v-card-title>Monthly Collections</v-card-title><v-card-text><div v-if="!monthly.length" class="empty">No collection data.</div><div v-for="row in monthly" :key="row.month" class="mb-4"><div class="d-flex justify-space-between caption"><span>{{ row.month }}</span><strong>{{ money(row.amount) }}</strong></div><v-progress-linear class="mt-1" rounded :value="percent(row.amount)" color="primary"/></div></v-card-text></v-card></v-col><v-col cols="12" md="6"><v-card outlined><v-card-title>Property Inventory</v-card-title><v-list dense><v-list-item v-for="row in inventory" :key="row.label"><v-list-item-content>{{ row.label }}</v-list-item-content><v-list-item-action><v-chip small outlined>{{ row.value }}</v-chip></v-list-item-action></v-list-item></v-list></v-card></v-col></v-row>
  </div>
</template>
<script>
import api from '../../../services/api'
export default {name:'Reports',data:()=>({loading:false,receivableLoading:false,error:'',metrics:{},monthly:[],inventory:[],receivables:[],overdueOnly:false,cards:[{label:'Sales Value',key:'sales_value',money:true},{label:'Collections',key:'collections',money:true},{label:'Receivables',key:'receivables',money:true},{label:'Overdue Amount',key:'overdue_amount',money:true}],receivableHeaders:[{text:'Customer',value:'booking.customer.name'},{text:'Property',value:'booking.property.property_number'},{text:'Due Date',value:'due_date'},{text:'Amount',value:'amount',align:'right'},{text:'Paid',value:'paid_amount',align:'right'},{text:'Remaining',value:'remaining_amount',align:'right'},{text:'Status',value:'status'}]}),computed:{max(){return Math.max(...this.monthly.map(r=>Number(r.amount||0)),1)}},mounted(){this.load()},filters:{dateOnly(v){return v?String(v).slice(0,10):''}},methods:{async load(){this.loading=true;this.error='';try{const r=await api.get('/sales/dashboard');const d=r.data||{};this.metrics=d.metrics||{};this.monthly=d.monthly_collections||[];const m=this.metrics;this.inventory=[{label:'Available',value:m.available_properties||0},{label:'Reserved',value:m.reserved_properties||0},{label:'Booked',value:m.booked_properties||0},{label:'Sold',value:m.sold_properties||0},{label:'Overdue Installments',value:m.overdue_count||0}];await this.loadReceivables()}catch(e){this.error=(e.response&&e.response.data&&e.response.data.message)||'Unable to load reports.'}finally{this.loading=false}},async loadReceivables(){this.receivableLoading=true;try{const r=await api.get('/sales/receivables',{params:{overdue:this.overdueOnly,per_page:100}});this.receivables=r.data.data||[]}catch(e){this.error=(e.response&&e.response.data&&e.response.data.message)||'Unable to load receivables.'}finally{this.receivableLoading=false}},isOverdue(i){return i&&i.due_date&&String(i.due_date).slice(0,10)<new Date().toISOString().slice(0,10)&&Number(i.remaining_amount)>0},money(v){return new Intl.NumberFormat('en-PK',{maximumFractionDigits:0}).format(Number(v||0))},percent(v){return Number(v||0)/this.max*100}}}
</script><style scoped>.page{width:100%}.hero{border-left:4px solid #165134}.empty{min-height:120px;display:flex;align-items:center;justify-content:center;color:#888}</style>
