<?php
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\Commission;
use Illuminate\Http\Request;
class CommissionController extends Controller{
 public function index(Request $r){$q=Commission::with(['booking.customer','booking.property','agent:id,name']);if($r->filled('agent_id'))$q->where('agent_id',$r->agent_id);if($r->filled('status'))$q->where('status',$r->status);return response()->json($q->latest()->paginate($r->integer('per_page',15)));}
 public function store(Request $r){$d=$r->validate(['booking_id'=>'required|exists:bookings,id','agent_id'=>'required|exists:users,id','percentage'=>'required|numeric|min:0|max:100','notes'=>'nullable|string']);$booking=\App\Models\Booking::findOrFail($d['booking_id']);if($booking->sales_agent_id && (int)$booking->sales_agent_id !== (int)$d['agent_id'])abort(422,'Commission agent must match the booking sales agent.');if(Commission::where('booking_id',$booking->id)->where('agent_id',$d['agent_id'])->whereIn('status',['pending','approved','paid'])->exists())abort(422,'A commission already exists for this booking and agent.');$base=(float)$booking->final_price;$d['base_amount']=$base;$d['commission_amount']=round($base*(float)$d['percentage']/100,2);$c=Commission::create($d);return response()->json(['message'=>'Commission created.','commission'=>$c->load(['booking.customer','booking.property','agent'])],201);}
 public function update(Request $r,Commission $commission){$d=$r->validate(['status'=>'required|in:pending,approved,paid,cancelled','notes'=>'nullable|string']);if($commission->status==='cancelled'&&$d['status']!=='cancelled')abort(422,'Cancelled commissions cannot be reopened.');if($commission->status==='paid'&&$d['status']!=='paid')abort(422,'Paid commissions cannot be moved backwards.');if($d['status']==='paid'&&$commission->status!=='approved')abort(422,'Only approved commissions can be marked paid.');if($d['status']==='approved')$d['approved_date']=now()->toDateString();if($d['status']==='paid')$d['paid_date']=now()->toDateString();$commission->update($d);return response()->json(['message'=>'Commission updated.','commission'=>$commission->fresh()->load(['booking','agent'])]);}
}
