<template>
  <div class="page">
    <v-card flat class="hero pa-5 mb-4"><div class="d-flex align-center"><div><div class="text-overline">PROJECT DELIVERY</div><h1 class="text-h5 font-weight-bold">Construction</h1><div class="grey--text">Monitor project status, budget and construction progress.</div></div><v-spacer/><v-btn icon :loading="loading" @click="load"><v-icon>mdi-refresh</v-icon></v-btn></div></v-card>
    <v-alert v-if="error" type="error" dense text>{{ error }}</v-alert>
    <v-row><v-col cols="12" sm="4"><v-card outlined><v-card-text><div class="caption grey--text">ACTIVE PROJECTS</div><div class="text-h5 font-weight-bold">{{ activeCount }}</div></v-card-text></v-card></v-col><v-col cols="12" sm="4"><v-card outlined><v-card-text><div class="caption grey--text">AVERAGE PROGRESS</div><div class="text-h5 font-weight-bold">{{ averageProgress }}%</div></v-card-text></v-card></v-col><v-col cols="12" sm="4"><v-card outlined><v-card-text><div class="caption grey--text">PROJECT BUDGET</div><div class="text-h5 font-weight-bold">{{ money(totalBudget) }}</div></v-card-text></v-card></v-col></v-row>
    <v-card flat outlined class="mt-4"><v-data-table :headers="headers" :items="projects" :loading="loading"><template v-slot:item.status="{item}"><v-chip x-small :color="statusColor(item.status)" dark>{{ label(item.status) }}</v-chip></template><template v-slot:item.construction_progress="{item}"><div style="min-width:150px"><div class="d-flex justify-space-between caption"><span>{{ Number(item.construction_progress || 0) }}%</span><span>{{ item.expected_completion_date || '' }}</span></div><v-progress-linear rounded :value="Number(item.construction_progress || 0)" color="primary"/></div></template><template v-slot:item.budget="{item}">{{ money(item.budget) }}</template><template v-slot:item.actual_cost="{item}">{{ money(item.actual_cost) }}</template><template v-slot:no-data><div class="pa-8 grey--text">No projects found.</div></template></v-data-table></v-card>
  </div>
</template>
<script>
import api from '../../../services/api'
export default {name:'Construction',data:()=>({loading:false,error:'',projects:[],headers:[{text:'Project',value:'name'},{text:'Status',value:'status'},{text:'Progress',value:'construction_progress',sortable:false},{text:'Budget',value:'budget',align:'right'},{text:'Actual Cost',value:'actual_cost',align:'right'}]}),computed:{activeCount(){return this.projects.filter(p=>['active','under_construction'].includes(p.status)).length},averageProgress(){if(!this.projects.length)return 0;return Math.round(this.projects.reduce((s,p)=>s+Number(p.construction_progress||0),0)/this.projects.length)},totalBudget(){return this.projects.reduce((s,p)=>s+Number(p.budget||0),0)}},mounted(){this.load()},methods:{async load(){this.loading=true;this.error='';try{const r=await api.get('/projects',{params:{per_page:100}});this.projects=r.data.data||r.data||[]}catch(e){this.error=e.response?.data?.message||'Unable to load construction projects.'}finally{this.loading=false}},money(v){return new Intl.NumberFormat('en-PK',{maximumFractionDigits:0}).format(Number(v||0))},label(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())},statusColor(v){return {active:'success',under_construction:'primary',completed:'blue-grey',on_hold:'orange',cancelled:'error',planning:'grey'}[v]||'grey'}}}
</script>
<style scoped>.page{width:100%}.hero{border-left:4px solid #165134}.page ::v-deep .v-data-table__wrapper{overflow-x:auto}</style>
