<template>
<div class="page">
<v-card flat class="hero pa-5 mb-4"><div class="d-flex align-center flex-wrap"><div><div class="text-overline">SALES</div><h1 class="text-h5 font-weight-bold">Bookings</h1><div class="grey--text">Manage reservations, confirmations and completed sales.</div></div><v-spacer/><v-btn color="#165134" dark depressed @click="openCreate"><v-icon left>mdi-bookmark-plus</v-icon>New Booking</v-btn></div></v-card>
<v-card flat class="pa-3 mb-4"><v-row dense align="center"><v-col cols="12" md="6"><v-text-field v-model="search" outlined dense clearable prepend-inner-icon="mdi-magnify" label="Search booking or customer" @keyup.enter="load" @click:clear="load"/></v-col><v-col cols="12" md="3"><v-select v-model="status" :items="statuses" outlined dense clearable label="Status" @change="load"/></v-col><v-col cols="12" md="3" class="text-right"><v-chip>{{items.length}} shown</v-chip></v-col></v-row></v-card>
<v-card flat><v-data-table :headers="headers" :items="items" :loading="loading" mobile-breakpoint="700"><template v-slot:item.status="{item}"><v-chip x-small dark :color="color(item.status)">{{item.status}}</v-chip></template><template v-slot:item.final_price="{item}">{{money(item.final_price)}}</template><template v-slot:item.remaining_amount="{item}"><span :class="{'error--text':Number(item.remaining_amount)>0}">{{money(item.remaining_amount)}}</span></template><template v-slot:item.actions="{item}"><v-btn v-if="item.status==='reserved'" icon small title="Confirm booking" @click="transition(item,'confirm')"><v-icon small>mdi-check</v-icon></v-btn><v-btn v-if="['reserved','confirmed'].includes(item.status)" icon small title="Cancel booking" @click="transition(item,'cancel')"><v-icon small>mdi-close</v-icon></v-btn><v-btn v-if="item.status==='confirmed' && Number(item.remaining_amount)<=0" icon small title="Complete sale" @click="transition(item,'complete')"><v-icon small>mdi-check-circle</v-icon></v-btn></template></v-data-table></v-card>
<v-dialog v-model="dialog" max-width="700"><v-card><v-card-title>New Booking<v-spacer/><v-btn icon @click="dialog=false"><v-icon>mdi-close</v-icon></v-btn></v-card-title><v-card-text><v-alert outlined type="info" dense>Only available properties can be reserved.</v-alert><v-row>
<v-col cols="12" md="6"><v-autocomplete v-model="form.customer_id" :items="customers" item-text="name" item-value="id" outlined dense clearable label="Customer *" :loading="loadingCustomers" prepend-inner-icon="mdi-account"/></v-col>
<v-col cols="12" md="6"><v-autocomplete v-model="form.property_id" :items="properties" item-text="property_number" item-value="id" outlined dense clearable label="Available Property *" :loading="loadingProperties" prepend-inner-icon="mdi-home-city"><template v-slot:item="{item}"><v-list-item-content><v-list-item-title>{{item.property_number}} — {{item.project ? item.project.name : 'Property'}}</v-list-item-title><v-list-item-subtitle>{{money(item.price)}} · {{item.status}}</v-list-item-subtitle></v-list-item-content></template></v-autocomplete></v-col>
<v-col cols="12" md="6"><v-autocomplete v-model="form.sales_agent_id" :items="agents" item-text="name" item-value="id" outlined dense clearable label="Sales Agent" :loading="loadingAgents" prepend-inner-icon="mdi-account-tie"/></v-col>
<v-col cols="12" md="6"><v-text-field v-model="form.discount" type="number" min="0" outlined dense label="Discount" prepend-inner-icon="mdi-sale"/></v-col>
<v-col cols="12"><v-textarea v-model="form.notes" outlined dense rows="2" label="Notes"/></v-col></v-row></v-card-text><v-card-actions><v-spacer/><v-btn text @click="dialog=false">Cancel</v-btn><v-btn color="#165134" dark :loading="saving" :disabled="!form.customer_id || !form.property_id" @click="save">Reserve Property</v-btn></v-card-actions></v-card></v-dialog>
</div></template>
<script>
import api from '../../../services/api'
export default {name:'Bookings',data(){return{loading:false,saving:false,dialog:false,search:'',status:null,items:[],customers:[],properties:[],agents:[],loadingCustomers:false,loadingProperties:false,loadingAgents:false,statuses:['reserved','confirmed','completed','cancelled'],headers:[{text:'Booking #',value:'booking_number'},{text:'Customer',value:'customer.name'},{text:'Property',value:'property.property_number'},{text:'Status',value:'status'},{text:'Final Price',value:'final_price'},{text:'Remaining',value:'remaining_amount'},{text:'Actions',value:'actions',sortable:false}],form:{customer_id:null,property_id:null,sales_agent_id:null,discount:0,notes:''}}},mounted(){this.load()},methods:{openCreate(){this.form={customer_id:null,property_id:null,sales_agent_id:null,discount:0,notes:''};this.dialog=true;this.loadLookups()},async loadLookups(){this.loadingCustomers=true;this.loadingProperties=true;this.loadingAgents=true;try{const [c,p,u]=await Promise.all([api.get('/customers',{params:{per_page:100}}),api.get('/properties',{params:{status:'available',per_page:100}}),api.get('/users',{params:{role:'Sales Agent',per_page:100}})]);this.customers=c.data.data||[];this.properties=(p.data.data||[]).filter(x=>x.status==='available');this.agents=u.data.data||[]}catch(e){this.$root.$emit('show-error','Unable to load booking selections.')}finally{this.loadingCustomers=false;this.loadingProperties=false;this.loadingAgents=false}},async load(){this.loading=true;try{const r=await api.get('/bookings',{params:{search:this.search,status:this.status,per_page:100}});this.items=r.data.data||[]}catch(e){this.$root.$emit('show-error','Unable to load bookings.')}finally{this.loading=false}},money(v){return new Intl.NumberFormat('en-PK',{maximumFractionDigits:0}).format(Number(v||0))},color(s){return{reserved:'orange',confirmed:'blue',completed:'success',cancelled:'grey'}[s]||'grey'},async save(){this.saving=true;try{await api.post('/bookings',this.form);this.dialog=false;await this.load()}catch(e){this.$root.$emit('show-error',e.response?.data?.message||'Unable to create booking.')}finally{this.saving=false}},async transition(item,action){const labels={confirm:'confirm this booking',cancel:'cancel this booking',complete:'complete this sale'};if(!window.confirm('Are you sure you want to '+labels[action]+'?'))return;try{await api.post('/bookings/'+item.id+'/'+action);await this.load()}catch(e){this.$root.$emit('show-error',e.response?.data?.message||'Unable to update booking.')}}}}
</script>
<style scoped>.page{width:100%}.hero{border-left:4px solid #165134}</style>