<template>
  <div class="page">
    <v-card flat class="hero pa-5 mb-4">
      <div class="d-flex align-center flex-wrap"><div><div class="text-overline">SALES CRM</div><h1 class="text-h5 font-weight-bold">Leads</h1><div class="grey--text">Track prospects from enquiry to conversion.</div></div><v-spacer/><v-btn color="#165134" dark depressed @click="dialog=true"><v-icon left>mdi-account-plus</v-icon>New Lead</v-btn></div>
    </v-card>
    <v-card flat class="pa-3 mb-4"><v-row dense align="center"><v-col cols="12" md="5"><v-text-field v-model="search" dense outlined clearable prepend-inner-icon="mdi-magnify" label="Search leads" @keyup.enter="load" @click:clear="load"/></v-col><v-col cols="12" md="3"><v-select v-model="status" :items="statuses" dense outlined clearable label="Status" @change="load"/></v-col><v-col cols="12" md="4" class="text-right"><v-chip class="mr-2">{{ total }} leads</v-chip><v-btn text @click="load"><v-icon left>mdi-refresh</v-icon>Refresh</v-btn></v-col></v-row></v-card>
    <v-card flat><v-data-table :headers="headers" :items="items" :loading="loading" :server-items-length="total" :options.sync="options" @update:options="load"><template v-slot:item.status="{item}"><v-chip x-small dark :color="statusColor(item.status)">{{ item.status }}</v-chip></template><template v-slot:item.actions="{item}"><v-btn icon small @click="edit(item)"><v-icon small>mdi-pencil</v-icon></v-btn></template></v-data-table></v-card>
    <v-dialog v-model="dialog" max-width="650"><v-card><v-card-title>{{ editing ? 'Edit Lead' : 'New Lead' }}<v-spacer/><v-btn icon @click="dialog=false"><v-icon>mdi-close</v-icon></v-btn></v-card-title><v-card-text><v-form><v-row><v-col cols="12" md="6"><v-text-field v-model="form.name" outlined dense label="Name *"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.phone" outlined dense label="Phone *"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.email" outlined dense label="Email"/></v-col><v-col cols="12" md="6"><v-select v-model="form.status" :items="statuses" outlined dense label="Status"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.source" outlined dense label="Source"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.interested_property" outlined dense label="Interested Property"/></v-col><v-col cols="12"><v-textarea v-model="form.notes" outlined dense rows="3" label="Notes"/></v-col></v-row></v-form></v-card-text><v-card-actions><v-spacer/><v-btn text @click="dialog=false">Cancel</v-btn><v-btn color="#165134" dark :loading="saving" @click="save">Save Lead</v-btn></v-card-actions></v-card></v-dialog>
  </div>
</template>
<script>
import api from '../../../services/api'
export default {name:'Leads',data(){return{loading:false,saving:false,dialog:false,editing:null,search:'',status:null,total:0,items:[],options:{page:1,itemsPerPage:15},statuses:['new','contacted','qualified','site_visit','negotiation','converted','lost'],headers:[{text:'Name',value:'name'},{text:'Phone',value:'phone'},{text:'Source',value:'source'},{text:'Status',value:'status'},{text:'Created',value:'created_at'},{text:'Actions',value:'actions',sortable:false}],form:{name:'',phone:'',email:'',source:'',interested_property:'',status:'new',notes:''}}},mounted(){this.load()},methods:{async load(){this.loading=true;try{const r=await api.get('/leads',{params:{search:this.search,status:this.status,page:this.options.page,per_page:this.options.itemsPerPage}});this.items=r.data.data||[];this.total=r.data.total||0}finally{this.loading=false}},edit(i){this.editing=i;this.form=Object.assign({},this.form,i);this.dialog=true},async save(){this.saving=true;try{if(this.editing)await api.put('/leads/'+this.editing.id,this.form);else await api.post('/leads',this.form);this.dialog=false;this.editing=null;await this.load()}catch(e){this.$root.$emit('show-error',e.response?.data?.message||'Unable to save lead.')}finally{this.saving=false}},statusColor(s){return{new:'grey',contacted:'blue',qualified:'indigo',site_visit:'orange',negotiation:'purple',converted:'success',lost:'error'}[s]||'grey'}}}
</script>
<style scoped>.page{width:100%}.hero{border-left:4px solid #165134}</style>
