<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\API\AuthController;
use App\Http\Controllers\API\BranchController;
use App\Http\Controllers\API\ProjectController;
use App\Http\Controllers\API\ProjectBlockController;
use App\Http\Controllers\API\PropertyController;
use App\Http\Controllers\API\PropertyImageController;
use App\Http\Controllers\API\PropertyDocumentController;
use App\Http\Controllers\API\PropertyFeatureController;
use App\Http\Controllers\API\PropertyStatusController;
use App\Http\Controllers\API\CustomerController;
use App\Http\Controllers\API\LeadController;
use App\Http\Controllers\API\SiteVisitController;
use App\Http\Controllers\API\BookingController;
use App\Http\Controllers\API\BookingStatusController;
use App\Http\Controllers\API\InstallmentPlanController;
use App\Http\Controllers\API\InstallmentController;
use App\Http\Controllers\API\PaymentController;
use App\Http\Controllers\API\CommissionController;
use App\Http\Controllers\API\SalesDashboardController;
use App\Http\Controllers\API\ExpenseController;

Route::prefix('auth')->group(function(){Route::post('/login',[AuthController::class,'login']);});
Route::middleware('auth:sanctum')->group(function(){
 Route::prefix('auth')->group(function(){Route::get('/me',[AuthController::class,'me']);Route::post('/logout',[AuthController::class,'logout']);});
 Route::apiResource('branches',BranchController::class)->only(['index','show']);
 Route::apiResource('projects',ProjectController::class);
 Route::apiResource('project-blocks',ProjectBlockController::class);
 Route::get('properties/inventory',[PropertyController::class,'inventory']); Route::apiResource('properties',PropertyController::class);
 Route::put('properties/{property}/status',[PropertyStatusController::class,'update']); Route::get('properties/{property}/status-history',[PropertyStatusController::class,'history']);
 Route::post('properties/{property}/images',[PropertyImageController::class,'store']); Route::delete('property-images/{image}',[PropertyImageController::class,'destroy']); Route::put('property-images/{image}/primary',[PropertyImageController::class,'primary']);
 Route::post('properties/{property}/documents',[PropertyDocumentController::class,'store']); Route::delete('property-documents/{document}',[PropertyDocumentController::class,'destroy']);
 Route::post('properties/{property}/features',[PropertyFeatureController::class,'store']); Route::delete('property-features/{feature}',[PropertyFeatureController::class,'destroy']);
 Route::apiResource('customers',CustomerController::class); Route::apiResource('leads',LeadController::class); Route::apiResource('site-visits',SiteVisitController::class);
 Route::apiResource('bookings',BookingController::class); Route::post('bookings/{booking}/confirm',[BookingStatusController::class,'confirm']); Route::post('bookings/{booking}/cancel',[BookingStatusController::class,'cancel']); Route::post('bookings/{booking}/complete',[BookingStatusController::class,'complete']);
 Route::get('sales/dashboard',[SalesDashboardController::class,'index']);
 Route::apiResource('installment-plans',InstallmentPlanController::class); Route::apiResource('installments',InstallmentController::class)->only(['index','show']); Route::apiResource('payments',PaymentController::class)->only(['index','store','show']); Route::get('payments/{payment}/receipt',[PaymentController::class,'receipt']); Route::apiResource('commissions',CommissionController::class)->only(['index','store','update']);
 Route::apiResource('expenses',ExpenseController::class);
});
