<template>
  <v-container fluid>
    <div class="d-flex align-center mb-6"><div><div class="text-h5 font-weight-bold">Property Details</div><div v-if="property" class="text-caption grey--text">{{ property.property_number }}</div></div><v-spacer/><v-btn text class="mr-2" @click="$router.push('/admin/properties')"><v-icon left>mdi-arrow-left</v-icon>Back</v-btn><v-btn v-if="property && $can('properties.edit')" color="#165134" dark :to="`/admin/properties/${property.id}/edit`"><v-icon left>mdi-pencil</v-icon>Edit</v-btn></div>
    <v-progress-linear v-if="loading" indeterminate color="#165134" class="mb-4" />
    <template v-if="property">
      <v-row><v-col cols="12" md="8"><v-card outlined><v-card-title><div><div class="text-h6">{{ property.property_number }}</div><div class="text-caption grey--text">{{ property.project ? property.project.name : '' }}</div></div><v-spacer/><v-chip :color="statusColor(property.status)" dark small>{{ statusText(property.status) }}</v-chip></v-card-title><v-divider/><v-card-text><v-row><v-col cols="6" md="3"><div class="caption grey--text">Property Type</div><div>{{ property.property_type }}</div></v-col><v-col cols="6" md="3"><div class="caption grey--text">Size</div><div>{{ property.size }} {{ property.size_unit }}</div></v-col><v-col cols="6" md="3"><div class="caption grey--text">Price</div><div>Rs. {{ formatNumber(property.price) }}</div></v-col><v-col cols="6" md="3"><div class="caption grey--text">Net Price</div><div class="text-h6 font-weight-bold">Rs. {{ formatNumber(property.net_price) }}</div></v-col></v-row><v-divider class="my-5"/><v-row><v-col cols="6" md="3"><div class="caption grey--text">Block</div><div>{{ property.block ? property.block.name : '-' }}</div></v-col><v-col cols="6" md="3"><div class="caption grey--text">Bedrooms</div><div>{{ property.bedrooms || '-' }}</div></v-col><v-col cols="6" md="3"><div class="caption grey--text">Bathrooms</div><div>{{ property.bathrooms || '-' }}</div></v-col><v-col cols="6" md="3"><div class="caption grey--text">Covered Area</div><div>{{ property.covered_area || '-' }} {{ property.covered_area_unit }}</div></v-col></v-row><v-divider class="my-5"/><div class="caption grey--text mb-2">Address</div><div>{{ property.address || '-' }}</div><div v-if="property.description" class="mt-5"><div class="caption grey--text mb-2">Description</div><div>{{ property.description }}</div></div><property-image-manager :property-id="property.id" class="mb-6" /></v-card-text></v-card></v-col>
        <v-col cols="12" md="4"><v-card outlined><v-card-title>Change Status</v-card-title><v-divider/><v-card-text><template v-if="$can('properties.edit')"><v-select v-model="newStatus" :items="statuses" item-text="text" item-value="value" label="Status" outlined dense/><v-textarea v-model="statusNotes" label="Notes" outlined rows="3"/><v-btn block color="#165134" dark :loading="statusSaving" @click="changeStatus">Update Status</v-btn></template><v-alert v-else type="info" text dense>You have view-only access to this property.</v-alert></v-card-text></v-card></v-col></v-row>
      <v-card outlined class="mt-5"><v-card-title>Features</v-card-title><v-divider/><v-card-text><v-chip v-for="feature in property.features" :key="feature.id" class="ma-1" outlined><v-icon left small>mdi-check-circle</v-icon>{{ feature.feature_name }}</v-chip><div v-if="!property.features || !property.features.length" class="grey--text">No features added.</div></v-card-text></v-card>
      <v-card outlined class="mt-5"><v-card-title>Status History</v-card-title><v-divider/><v-card-text><v-timeline dense><v-timeline-item v-for="item in property.status_histories" :key="item.id" small><strong>{{ statusText(item.new_status) }}</strong><div class="caption grey--text">{{ item.old_status ? statusText(item.old_status) : 'Created' }} → {{ statusText(item.new_status) }}</div><div v-if="item.notes" class="mt-1">{{ item.notes }}</div></v-timeline-item></v-timeline></v-card-text></v-card>
    </template>
    <v-snackbar v-model="snackbar" :color="snackbarColor" bottom right>{{ snackbarText }}</v-snackbar>
  </v-container>
</template>
<script>
import api from '../../../services/api'
import PropertyImageManager from './PropertyImageManager.vue'
export default {name:'PropertyDetails',components:{PropertyImageManager},data(){return{loading:false,statusSaving:false,property:null,newStatus:null,statusNotes:'',statuses:[{text:'Available',value:'available'},{text:'Reserved',value:'reserved'},{text:'Booked',value:'booked'},{text:'Sold',value:'sold'},{text:'Under Construction',value:'under_construction'},{text:'Rented',value:'rented'},{text:'Unavailable',value:'unavailable'},{text:'Cancelled',value:'cancelled'}],snackbar:false,snackbarText:'',snackbarColor:'success'}},created(){this.loadProperty()},methods:{async loadProperty(){this.loading=true;try{const response=await api.get(`/properties/${this.$route.params.id}`);this.property=response.data.property;this.newStatus=this.property.status}catch(error){console.error(error);this.showMessage('Unable to load property.','error')}finally{this.loading=false}},async changeStatus(){if(!this.newStatus||!this.$can('properties.edit'))return;this.statusSaving=true;try{await api.put(`/properties/${this.property.id}/status`,{status:this.newStatus,notes:this.statusNotes});this.statusNotes='';await this.loadProperty();this.showMessage('Property status updated successfully.','success')}catch(error){console.error(error);this.showMessage((error.response&&error.response.data&&error.response.data.message)||'Unable to update status.','error')}finally{this.statusSaving=false}},statusText(status){const item=this.statuses.find(x=>x.value===status);return item?item.text:status},statusColor(status){return({available:'green',reserved:'orange',booked:'blue',sold:'red',under_construction:'purple',rented:'teal',unavailable:'grey',cancelled:'black'})[status]||'grey'},formatNumber(value){return Number(value||0).toLocaleString()},showMessage(message,color){this.snackbarText=message;this.snackbarColor=color;this.snackbar=true}}}
</script>
