<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,Arial,sans-serif;font-size:11px;color:#222}.header{border-bottom:3px solid #165134;padding-bottom:12px}.logo{height:70px;float:right}.brand{font-size:20px;font-weight:bold;color:#165134}.muted{color:#666}.summary{width:100%;margin:18px 0;border-collapse:collapse}.summary td{padding:10px;border:1px solid #ddd}.value{font-size:15px;font-weight:bold;color:#165134}table.data{width:100%;border-collapse:collapse;margin-top:8px}.data th,.data td{border:1px solid #ddd;padding:6px}.data th{background:#165134;color:white}.section{font-size:15px;font-weight:bold;margin-top:20px}.footer{margin-top:25px;border-top:1px solid #ddd;padding-top:8px;text-align:center;color:#777;font-size:9px}
</style></head><body>
<div class="header"><img class="logo" src="{{ public_path('images/zeerak-logo.jpeg') }}"><div class="brand">ZeeraK Real Estate & Builders</div><div>Customer Account Statement</div><div class="muted">Generated {{ now()->format('d M Y H:i') }}</div></div>
<h2>{{ $customer['name'] }}</h2><div>{{ $customer['customer_number'] }} · {{ $customer['phone'] }} @if(!empty($customer['cnic'])) · CNIC {{ $customer['cnic'] }} @endif</div>
<table class="summary"><tr><td>Booked Value<br><span class="value">PKR {{ number_format($summary['booked_value'],2) }}</span></td><td>Paid<br><span class="value">PKR {{ number_format($summary['paid'],2) }}</span></td><td>Outstanding<br><span class="value">PKR {{ number_format($summary['outstanding'],2) }}</span></td><td>Overdue<br><span class="value">PKR {{ number_format($summary['overdue'],2) }}</span></td></tr></table>
<div class="section">Bookings</div><table class="data"><tr><th>Booking</th><th>Property</th><th>Date</th><th>Value</th><th>Paid</th><th>Balance</th></tr>@foreach($bookings as $x)<tr><td>{{ $x['booking_number'] }}</td><td>{{ data_get($x,'property.property_number','—') }}</td><td>{{ substr($x['booking_date'],0,10) }}</td><td>{{ number_format($x['final_price'],2) }}</td><td>{{ number_format($x['paid_amount'],2) }}</td><td>{{ number_format($x['remaining_amount'],2) }}</td></tr>@endforeach</table>
<div class="section">Payments</div><table class="data"><tr><th>Receipt</th><th>Date</th><th>Method</th><th>Amount</th></tr>@foreach($payments as $x)<tr><td>{{ $x['receipt_number'] }}</td><td>{{ substr($x['payment_date'],0,10) }}</td><td>{{ ucwords(str_replace('_',' ',$x['payment_method'])) }}</td><td>{{ number_format($x['amount'],2) }}</td></tr>@endforeach</table>
<div class="section">Installments</div><table class="data"><tr><th>#</th><th>Booking</th><th>Due Date</th><th>Amount</th><th>Paid</th><th>Balance</th><th>Status</th></tr>@foreach($installments as $x)<tr><td>{{ $x['installment_number'] }}</td><td>{{ data_get($x,'booking.booking_number','—') }}</td><td>{{ substr($x['due_date'],0,10) }}</td><td>{{ number_format($x['amount'],2) }}</td><td>{{ number_format($x['paid_amount'],2) }}</td><td>{{ number_format($x['remaining_amount'],2) }}</td><td>{{ ucfirst($x['status']) }}</td></tr>@endforeach</table>
<div class="footer">ZeeraK Real Estate & Builders · Electronically generated customer statement</div></body></html>