<template>
<v-app>
<v-navigation-drawer v-model="drawer" app :dark="darkMode" :mini-variant="compactMode" :width="280">
<div class="pa-5"><div class="d-flex align-center"><v-icon color="primary" size="36">mdi-home-city</v-icon><div v-if="!compactMode" class="ml-3"><div class="font-weight-bold">ZEERAK</div><small>Real Estate & Builders</small></div></div></div><v-divider/>
<v-list nav dense>
<v-list-item v-if="$can('dashboard.view')" to="/admin/dashboard" link exact><v-list-item-icon><v-icon>mdi-view-dashboard</v-icon></v-list-item-icon><v-list-item-content v-if="!compactMode"><v-list-item-title>Dashboard</v-list-item-title></v-list-item-content></v-list-item>
<v-list-group v-if="$can('users.view') || $can('roles.view')" prepend-icon="mdi-shield-account" no-action><template v-slot:activator><v-list-item-title v-if="!compactMode">User Management</v-list-item-title></template><v-list-item v-if="$can('users.view')" to="/admin/users" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Users</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('roles.view')" to="/admin/roles" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Roles & Permissions</v-list-item-title></v-list-item-content></v-list-item></v-list-group>
<v-list-group v-if="$can('projects.view') || $can('properties.view')" prepend-icon="mdi-home-city" no-action><template v-slot:activator><v-list-item-title v-if="!compactMode">Real Estate</v-list-item-title></template><v-list-item v-if="$can('projects.view')" to="/admin/projects" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Projects</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('projects.view')" to="/admin/blocks" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Blocks</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('properties.view')" to="/admin/properties" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Properties</v-list-item-title></v-list-item-content></v-list-item></v-list-group>
<v-list-group v-if="$can('customers.view') || $can('leads.view') || $can('site_visits.view')" prepend-icon="mdi-account-group" no-action><template v-slot:activator><v-list-item-title v-if="!compactMode">CRM</v-list-item-title></template><v-list-item v-if="$can('customers.view')" to="/admin/customers" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Customers</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('leads.view')" to="/admin/leads" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Leads</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('site_visits.view')" to="/admin/site-visits" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Site Visits</v-list-item-title></v-list-item-content></v-list-item></v-list-group>
<v-list-group v-if="$can('sales.view') || $can('payments.view') || $can('installments.view') || $can('commissions.view') || $can('expenses.view') || $can('dashboard.view')" prepend-icon="mdi-cash-multiple" no-action><template v-slot:activator><v-list-item-title v-if="!compactMode">Sales & Finance</v-list-item-title></template><v-list-item v-if="$can('dashboard.view')" to="/admin/sales/dashboard" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Sales Dashboard</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('sales.view')" to="/admin/bookings" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Bookings</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('payments.view')" to="/admin/payments" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Payments</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('installments.view')" to="/admin/installments" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Installments</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('commissions.view')" to="/admin/commissions" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Commissions</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('expenses.view')" to="/admin/expenses" link><v-list-item-content v-if="!compactMode"><v-list-item-title>Expenses</v-list-item-title></v-list-item-content></v-list-item></v-list-group>
<v-list-item v-if="$can('construction.view')" to="/admin/construction" link><v-list-item-icon><v-icon>mdi-hard-hat</v-icon></v-list-item-icon><v-list-item-content v-if="!compactMode"><v-list-item-title>Construction</v-list-item-title></v-list-item-content></v-list-item><v-list-item v-if="$can('reports.view')" to="/admin/reports" link><v-list-item-icon><v-icon>mdi-file-chart</v-icon></v-list-item-icon><v-list-item-content v-if="!compactMode"><v-list-item-title>Reports</v-list-item-title></v-list-item-content></v-list-item><v-divider class="my-3"/><v-list-item v-if="$can('settings.view')" to="/admin/settings" link><v-list-item-icon><v-icon>mdi-cog</v-icon></v-list-item-icon><v-list-item-content v-if="!compactMode"><v-list-item-title>Settings</v-list-item-title></v-list-item-content></v-list-item>
</v-list></v-navigation-drawer>
<v-app-bar app flat outlined><v-app-bar-nav-icon @click="drawer=!drawer"/><v-toolbar-title class="font-weight-medium">{{ pageTitle }}</v-toolbar-title><v-spacer/><v-btn icon @click="toggleDarkMode"><v-icon>{{ darkMode?'mdi-weather-sunny':'mdi-weather-night' }}</v-icon></v-btn><v-menu offset-y><template v-slot:activator="{on,attrs}"><v-btn text v-bind="attrs" v-on="on"><v-avatar size="34" color="primary"><span class="white--text">{{ initials }}</span></v-avatar><span class="ml-2 hidden-sm-and-down">{{ userName }}</span><v-icon right>mdi-chevron-down</v-icon></v-btn></template><v-list><v-list-item @click="logout"><v-list-item-icon><v-icon>mdi-logout</v-icon></v-list-item-icon><v-list-item-content><v-list-item-title>Logout</v-list-item-title></v-list-item-content></v-list-item></v-list></v-menu></v-app-bar>
<v-main><v-container fluid class="pa-6"><router-view/></v-container></v-main></v-app>
</template>
<script>
export default {name:'AdminLayout',data(){return{drawer:true,darkMode:localStorage.getItem('zeerak_dark_mode')==='1',compactMode:localStorage.getItem('zeerak_compact_nav')==='1'}},computed:{user(){return this.$store.getters['auth/user']},userName(){return this.user?this.user.name:'User'},initials(){if(!this.user)return'U';return this.user.name.split(' ').map(n=>n.charAt(0)).join('').substring(0,2).toUpperCase()},pageTitle(){const titles={dashboard:'Dashboard','sales-dashboard':'Sales Dashboard',users:'Users',roles:'Roles & Permissions',projects:'Projects','project-create':'Create Project','project-edit':'Edit Project',blocks:'Project Blocks',properties:'Property Inventory','property-create':'Create Property','property-details':'Property Details','property-edit':'Edit Property',customers:'Customers',leads:'Leads','site-visits':'Site Visits',bookings:'Bookings',payments:'Payments',installments:'Installments',commissions:'Commissions',expenses:'Expenses',construction:'Construction',reports:'Reports','financial-audit':'Financial Audit',settings:'Settings'};return titles[this.$route.name]||'Zeerak ERP'}},mounted(){this.$vuetify.theme.dark=this.darkMode},methods:{toggleDarkMode(){this.darkMode=!this.darkMode;this.$vuetify.theme.dark=this.darkMode;localStorage.setItem('zeerak_dark_mode',this.darkMode?'1':'0')},async logout(){await this.$store.dispatch('auth/logout');this.$router.push({name:'login'})}}}
</script>
